#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$crawler = new \Zeroplex\Crawler\Crawler();

$crawler->addHandler(new \Crawler\BlogHandler());

$crawler->setMaxConcurrent(3);

$crawler->run('https://blog.zeroplex.tw');
